### ISSUE TITLE
[bug] HTTP Error 500 after changing settings and restarting

### ISSUE THREAD

**Issue by Wit4r7** [crocodilestick/Calibre-Web-Automated#108]
**Describe the bug**
After enabling the upload function by user in the basic configuratio, turning on the Thumbnail creation, uploading and fetching some metdata and restarting the container, I got an HTTP 500 Internal server error. 

```
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 806, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 417, in render_books_list
return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
cwa_update_notification()
File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
update_available, current_verision, tag_name = cwa_update_available()
File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
tag_name = response.json()['tag_name']
KeyError: 'tag_name'
```

**To Reproduce**
Not sure. As told above. I was changing some settings and updating some covers. I then restarted the container and can't access it now. 

**Expected behavior**
Starting the server :) 

**Screenshots**

**Configuration(please complete the following information):**
Running on a Synology DS720+ with DSM 7.2.1-69057 V5
Image version: 2.0.1

**Additional context**
Calibre-web.log

```
[2024-10-12 14:19:20,789]  INFO {cps.server:219} Starting Gevent server on [::]:8083
[2024-10-12 14:19:27,414] ERROR {cps.db:882} Author America's Test Kitchen not found to display name in right order
[2024-10-12 14:19:27,445] ERROR {cps.db:882} Author Name, Vorname not found to display name in right order
[2024-10-12 14:19:27,453] ERROR {cps.db:882} Author Tim Anderson not found to display name in right order
[2024-10-12 14:19:27,470] ERROR {cps.db:882} Author Kreischer, Lisette and Schuttelaar, Marcel not found to display name in right order
[2024-10-12 14:19:27,664] ERROR {cps:1414} Exception on / [GET]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 806, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 417, in render_books_list
    return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
  File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
    cwa_update_notification()
  File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
    update_available, current_verision, tag_name = cwa_update_available()
  File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
    tag_name = response.json()['tag_name']
KeyError: 'tag_name'
[2024-10-12 14:19:28,887] ERROR {cps.db:882} Author America's Test Kitchen not found to display name in right order
[2024-10-12 14:19:28,908] ERROR {cps.db:882} Author Name, Vorname not found to display name in right order
[2024-10-12 14:19:28,912] ERROR {cps.db:882} Author Tim Anderson not found to display name in right order
[2024-10-12 14:19:28,925] ERROR {cps.db:882} Author Kreischer, Lisette and Schuttelaar, Marcel not found to display name in right order
[2024-10-12 14:19:29,084] ERROR {cps:1414} Exception on / [GET]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 806, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 417, in render_books_list
    return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
  File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
    cwa_update_notification()
  File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
    update_available, current_verision, tag_name = cwa_update_available()
  File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
    tag_name = response.json()['tag_name']
KeyError: 'tag_name'
[2024-10-12 14:19:48,735] ERROR {cps.db:882} Author America's Test Kitchen not found to display name in right order
[2024-10-12 14:19:48,756] ERROR {cps.db:882} Author Name, Vorname not found to display name in right order
[2024-10-12 14:19:48,762] ERROR {cps.db:882} Author Tim Anderson not found to display name in right order
[2024-10-12 14:19:48,775] ERROR {cps.db:882} Author Kreischer, Lisette and Schuttelaar, Marcel not found to display name in right order
[2024-10-12 14:19:48,946] ERROR {cps:1414} Exception on / [GET]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 806, in index
    return render_books_list("newest", sort_param, 1, page)
  File "/app/calibre-web/cps/web.py", line 417, in render_books_list
    return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
  File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
    cwa_update_notification()
  File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
    update_available, current_verision, tag_name = cwa_update_available()
  File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
    tag_name = response.json()['tag_name']
KeyError: 'tag_name'
[2024-10-12 14:22:28,827] ERROR {cps.db:882} Author America's Test Kitchen not found to display name in right order
[2024-10-12 14:22:28,849] ERROR {cps.db:882} Author Name, Vorname not found to display name in right order
[2024-10-12 14:22:28,853] ERROR {cps.db:882} Author Tim Anderson not found to display name in right order
[2024-10-12 14:22:28,867] ERROR {cps.db:882} Author Kreischer, Lisette and Schuttelaar, Marcel not found to display name in right order
```

The full log is attached
[calibre-web.log](https://github.com/user-attachments/files/17350041/calibre-web.log)

Docker-Compose:
```
---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1028
      - PGID=911
      - TZ=Europe/Berlin
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - /volume1/docker/calibreauto:/config
      - /volume1/books/calibre:/calibre-library
      - /volume1/books/AutoImport:/cwa-book-ingest
    ports:
      - 8083:8083
    restart: unless-stopped
```

**Comment by jmarmstrong1207** [comment]
This error has been fixed in the latest dev image:
` image: crocodilestick/calibre-web-automated:dev`

This is our release candidate and will be released to `latest` in the future
