### ISSUE TITLE
[bug] Cannot access the Web interface if ratelimited by github.

### ISSUE THREAD

**Issue by Buco7854** [crocodilestick/Calibre-Web-Automated#70]
**Describe the bug**
Sometimes I get this error message. It is caused by the fact that i get rate-limited by github api. A simple fix would be to check if the 'tag_name' is present and if not just act as if it was the same version.

```
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 806, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 417, in render_books_list
return render_title_template('index.html', random=random, entries=entries, pagination=pagination,
File "/app/calibre-web/cps/render_template.py", line 153, in render_title_template
cwa_update_notification()
File "/app/calibre-web/cps/render_template.py", line 141, in cwa_update_notification
update_available, current_verision, tag_name = cwa_update_available()
File "/app/calibre-web/cps/render_template.py", line 119, in cwa_update_available
tag_name = response.json()['tag_name']
KeyError: 'tag_name'
```

**To Reproduce**
Go to any page
**Expected behavior**
Display the page as normal

**Configuration(please complete the following information):**
 - OS: Debian
 - Version 2.0.1

**Additional context**
Cannot describe how to reproduce clearly, it seems to happen randomly.

**Comment by crocodilestick** [comment]
@Buco7854 closed thanks to the merge of your PR fixing the issue!
